'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var APDSchema = Schema({
        codigo_ap: String,
        fecha: String,
        tipo: String,
        tipo_numero: String,
        tipo_fecha: String,
        apellidos: String,
        nombres: String,
        ci_per: String,
        quipux: String,
        no_af_iess: String,
        vigencia: String,
        explicacion: String,
        motivo: String,
        motivoExtra: String,
        proceso_sa: String,
        sbp_sa: String,
        puesto_sa: String,
        lugar_de_trabajo_sa: String,
        salario_sa: String,
        partida_presupuestaria_sa: String,
        proceso_sp: String,
        sbp_sp: String,
        puesto_sp: String,
        lugar_de_trabajo_sp: String,
        salario_sp: String,
        partida_presupuestaria_sp: String,
        af_numero: String,
        af_fecha: String,
        activa: {type: Boolean, default: false},
        rec_hum: String,
        aut_nom: String,
        res_reg: String,
        caucion: String,
        caucion_fecha: String,
        caucion_exp: String,
        remplaza: String,
        rem_puesto: String,
        ceso_fun: String,
        num_ac_rem: String,
        fec_ac_rem: String,
        afi_col: String,
        cod_rem: String,
        fecha_rem: String,
        lugar: String,
        fecha_fi: String,
        codigo_rh: String,
        nombre_pc: String,
        cedula_pc: String,
        fecha_activacion: String,
        autor: { type: Schema.ObjectId, ref: 'funcionario'}
});

module.exports = mongoose.model('accion_de_personal', APDSchema);